### ISSUE TITLE
Silent After Death

### ISSUE THREAD

**Issue by LittleSeaBisket** [ege-adam/MoreScreams#3]
Hello!

I played with a small group and came across an issue. After a player dies and then respawns, the other party members were unable to hear them.

**Comment by ege-adam** [comment]
Thanks for the feedback. I'll look into that. Are you sure that you are on the latest release?

**Comment by LittleSeaBisket** [comment]
I believe so, it say 1.0.1. I use r2modman and have a few other mods installed so I am not sure if that might have something to do with it as well.

**Comment by ege-adam** [comment]
Yes, 1.0.1 is latest. Would you mind sharing bepinex logs?  I was not able to reproduce the issue. So it would be really helpful if you can send the logs.

**Comment by ege-adam** [comment]
I still need logs or reproduce the bug to properly investigate the issue. Meanwhile you can try this beta build, which has potential fix for bug:
[1.0.2-beta](https://github.com/ege-adam/MoreScreams/releases/tag/1.0.2-beta)

**Comment by ege-adam** [comment]
Here the another beta with hardened protection against this bug:
  [1.0.2-beta.2](https://github.com/ege-adam/MoreScreams/releases/tag/1.0.2-beta.2)

**Comment by LittleSeaBisket** [comment]
Hello!

I apologize it’s taken me so long to respond. As soon as I get home I will
work on getting the logs. Is there a preferred way to get them to you?

**Comment by ege-adam** [comment]
You can just upload them to here. Thanks a lot!

**Comment by LittleSeaBisket** [comment]
I did some testing to recreate what happened and from what I can tell it works with 'more company' but not the 'biggerlobby' mod. 
[Error Logs for Lethal Company.docx](https://github.com/ege-adam/MoreScreams/files/13552440/Error.Logs.for.Lethal.Company.docx)

**Comment by ege-adam** [comment]
Thanks for showing the right direction, I've fixed the problem. It was indeed because of the BiggerLobby. Apparently a method in biggerlobby were generating errors, it was preventing method from my mod to run. I've added priority, to make my method run before BiggerLobby. I will get in touch with dev of the BiggerLobby.

[1.0.2](https://github.com/ege-adam/MoreScreams/releases/tag/1.0.2)

I will close the issue for now. Feel free to re-open it if its not fixed with latest release.

**Comment by lucyd-dev** [comment]
Heya,
I guess your mod is broken again with the latest version v64. Everytime someone dies and respawns, we cant hear them anymore. See below why Im thinking its this mod that causes this problem and I also attached my full last log, where that happend.

> [Info   :   Coroner] [REPORT] Player 0 is dead! Replacing notes with Cause of Death...
[Debug  :   Coroner] Player 0 has no custom cause of death stored! Using fallback...
[Info   :   Coroner] [REPORT] Player 1 has notes, don't override them...
[Info   :   Coroner] [REPORT] Player 2 has notes, don't override them...
[Info   :   Coroner] [REPORT] Player 3 is dead! Replacing notes with Cause of Death...
[Debug  :   Coroner] Player 3 has custom cause of death stored! DeathPitFacilityCatwalkJump
[Info   :   Coroner] Player 4 is not controlled by a player. Skipping...
[Info   :   Coroner] Player 5 is not controlled by a player. Skipping...
[Info   :   Coroner] Player 6 is not controlled by a player. Skipping...
[Info   :   Coroner] Player 7 is not controlled by a player. Skipping...
[Debug  :   Coroner] Clearing cause of death for player 0
[Debug  :   Coroner] Clearing cause of death for player 1
[Debug  :   Coroner] Clearing cause of death for player 2
[Debug  :   Coroner] Clearing cause of death for player 3
[Debug  :   Coroner] Clearing cause of death for player 4
[Debug  :   Coroner] Clearing cause of death for player 5
[Debug  :   Coroner] Clearing cause of death for player 6
[Debug  :   Coroner] Clearing cause of death for player 7
[Info   : Unity Log] Scrap collected: 759
[Info   : Unity Log] Called teleport function on Player
**[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
MoreScreams.Patches.AudioConfig.get_DeadBodyT () (at <28a666d2396e45d69eac02c371e5e1a6>:IL_0000)
MoreScreams.Patches.UpdatePlayerVoiceEffectsPatch.UpdatePlayersStatus () (at <28a666d2396e45d69eac02c371e5e1a6>:IL_005E)
MoreScreams.Patches.UpdatePlayerVoiceEffectsPatch+<UpdateNumerator>d__6.MoveNext () (at <28a666d2396e45d69eac02c371e5e1a6>:IL_003E)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)**

[voice-bug.log](https://github.com/user-attachments/files/16923920/voice-bug.log)

**Comment by chrispavs** [comment]
Can confirm that this happened to my friends and I as well. Disabling this mod caused the issue to go away indefinitely.
